; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env:esp32-s3-devkitc1-n4r8]
platform = espressif32
board = esp32-s3-devkitc1-n4r8
board_build.f_cpu = 240000000L
framework = arduino
board_build.partitions = custom_partitions.csv
build_unflags = 
	-std=gnu++11
build_flags = 
	-std=gnu++17
	-DBOARD_HAS_PSRAM
	-DARDUINO_USB_CDC_ON_BOOT=1
	-DARDUINO_USB_MODE=1
	
	-DLV_CONF_INCLUDE_SIMPLE
	-DLV_CONF_PATH="${PROJECT_DIR}/include/lv_conf.h"
	
	-O2
	-DCORE_DEBUG_LEVEL=3
	
	-Wno-narrowing
	
	-DCONFIG_IDF_TARGET_ESP32S3=1
	-Dtypeof=__typeof__
	-D__extension__=__extension__
	
	-DARDUINO_GFX_LIBRARY_MINIMAL
	
	; MASTER_PLAN: Uncomment to enable new architecture
	; -DUSE_NEW_ARCHITECTURE
lib_deps = 
	moononournation/GFX Library for Arduino@1.4.7
	lvgl/lvgl@^8.3.11
	bblanchon/ArduinoJson@^7.0.0
	gilmaimon/ArduinoWebsockets@^0.5.3

lib_extra_dirs = 
	${PROJECT_DIR}/lib

; Upload configuration (Auto-detect active COM port)
upload_speed = 921600
;upload_port = COM13
upload_flags = 
	--before=default_reset
	--after=hard_reset
	--chip=esp32s3

; Serial Monitor configuration (COM8)
;monitor_port = COM8
monitor_speed = 115200
monitor_dtr = 0
monitor_rts = 0
monitor_filters = esp32_exception_decoder

; Debug configuration
debug_tool = esp-builtin
debug_init_break = tbreak setup
